### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by happy-lifi** [megvii-research/HomoGAN#1]
Thank you for your awesome work. When will you release your full code?

**Comment by MingboHong** [comment]
> Thank you for your awesome work. When will you release your full code?

Hi, thank you for your interest, our code has been released.

**Comment by happy-lifi** [comment]
> 

Very good. How long to train?

**Comment by MingboHong** [comment]
> > 
> 
> Very good. How long to train?

pretrain phase: 4 2080ti cost 5*24 hours
