### ISSUE TITLE
Code opening

### ISSUE THREAD

**Issue by Wang-XingYi** [megvii-research/HomoGAN#2]
I am deeply attracted by your thoughts and look forward to your code opening as soon as possible, so that I can have a deeper understanding of your thoughts.

**Comment by MingboHong** [comment]
> I am deeply attracted by your thoughts and look forward to your code opening as soon as possible, so that I can have a deeper understanding of your thoughts.

https://github.com/megvii-research/HomoGAN/issues/2#issue-1321831591

**Comment by Wang-XingYi** [comment]
Thank you again for your contribution！
